import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English Translations
        'en_US': {
          'winter_mode': 'Winter Mode',
          'Thermostat Error': 'Thermostat Error',
          'enable': 'Setting Enabled',
          'disable': 'Setting Disabled',
          'wrong_password': 'Wrong Password',
          'low_pressure': 'Low Pressure',
          'high_pressure': 'High Pressure',
          'home': 'Home',
          'device': 'Device',
          'add_devices': 'Add Devices',
          'me': 'Me',
          'dashboard_item_opacity': 'Dashboard Item Opacity',
          'device_item_opacity': 'Device Item Opacity',
          'select_season': 'Select Season',
          'summer': 'Summer',
          'winter': 'Winter',
          'on': 'Running',
          'off': 'Stopped',
          'set_point': 'Set Point',
          'supply_cfm': 'Supply CFM',
          'signout': 'Sign Out',
          'value': 'Value',
          'set_temperature': 'Set Temperature',
          'delete_device_prompt':
              'Are you sure you want to delete this device?',
          'cancel': 'Cancel',
          'delete': 'Delete',
          'delete_device': 'Delete Device',
          'Schedule': 'Schedule',
          'CFM': 'CFM',
          'Mode': 'Mode',
          'Season': 'Season',
          'Switch': 'Switch',
          'Room Temp.': 'Room Temp.',
          'Temp.': 'Temp.',
          'Enter Password': 'Enter Password',
          'Submit': 'Submit',
          'device_list': 'Device List',
          'summer_mode': 'Summer Mode',
          'aqua': 'AQUA',
          'water_level': 'Water Level',
          'hi': 'FULL',
          'mid': 'MID',
          'low': 'LOW',
          'high': 'High',
          'cooler': 'Cooler',
          'boiler': 'Boiler',
          'comfort': 'Comforter',
          'booster': 'Booster',
          'makeup': 'MakeUp',
          'recirculor': 'Circulation',
          'settings': 'System Settings',
          'compressor': 'Compressor',
          'Target': 'Target Temp',
          'temperature': 'Temperature',
          'prsw': 'Pressure Switch',
          'suction': 'Suction',
          'discharge': 'Discharge',
          'supply': 'Supply',
          'return': 'Return',
          'pressure': 'Pressure',
          'oil': 'Oil',
          'phase_1': 'Phase 1',
          'phase_2': 'Phase 2',
          'phase_3': 'Phase 3',
          'temperatures': 'Temperatures',
          'pressures': 'Pressures',
          'currents': 'Currents',
          'return_setting': 'Return Setting',
          'supply_setting': 'Supply Setting',
          'suction_setting': 'Suction Setting',
          'discharge_setting': 'Discharge Setting',
          'low_temperature': 'Low Temperature',
          'high_temperature': 'High Temperature',
          'compressor_status': 'System Status',
          'suction_pressure_setting': 'Suction Pressure Setting',
          'discharge_pressure_setting': 'Discharge Pressure Setting',
          'oil_pressure_setting': 'Oil Pressure Setting',
          'current_setting': 'Current Setting',
          'high_ampere': 'High Ampere',
          'close': 'Close',
          'open': 'Open',
          'fan_controller': 'Fan Control',
          'pump_controller': 'Pump Control',
          'qr_code_scanner': 'QR Code Scanner',
          'home_pages': 'Home Page',
          'dark_mode': 'Dark Mode',
          'view_account': 'View Account',
          'bita_homes': 'BITA HOME',
          'name': 'Name',
          'edit_name': 'Edit Name',
          'enter_new_name': 'Enter new name',
          'save': 'Save',
          'logout': 'Logout',
          'online': 'Online',
          'offline': 'Offline',
          'ok': 'Ok',
          'password': 'Password',
          'unlock': 'Unlock',
          'error': 'Error',
          'days': 'Days',
          'hours': 'Hours',
          'enable_button_to_set_schedule': 'Enable button to set schedule',
          'schedule_damper': 'Damper Scheduling',
          'slider_locked': 'Slider locked',
          'cfm_protection': 'CFM Protection',
          'temp': 'Temp',
          'adjusting': 'Adjusting',
          'confirm_proceed': 'Are you sure you want to proceed?',
          'confirm_enable': 'Enable\nOil Pressure Switch',
          'confirm_disable': 'Disable\nOil Pressure Switch',
          'sensor': 'Sensor',
          'dischargeSwitch': 'Discharge Switch',
          'suctionSwitch': 'Suction Switch',
          'viewAccount': 'View Account',
          'oilPressureSensor': 'Oil Pressure Sensor',
          'oilPressureSwitch': 'Oil Pressure Switch',
          'Power': 'Operation',
          'language': 'Language',
          'automateControl': 'Automate the Control',
          'fan': 'Fan Status',
          'pump': 'Pump Status',
          'Alert Temperature': 'Alert Temperature',
          'Set Point': 'Set Point',
          'systemOff': 'System OFF',
          'ON': 'ON',
          'OFF': 'OFF',
          'waterTemp': 'Water Temp : ',
          'waterTank': 'Water Tank',
          'editDeviceName': 'Edit Device Name',
          'autoStopped': 'Auto Stopped',
          'systemTempC': 'System Temperatures (°C)',
          'systemTempF': 'System Temperatures (°F)',
          'systemPressurePsi': 'System Pressures (PSI)',
          'systemPressureBar': 'System Pressures (Bar)',
          'compressorCurrent': 'Compressor Current (A)',
          'pressureSwitches': 'Pressure Switches',
          'returnSp': 'Return (SP)',
          'setPoint': 'SetPoint :',
          'alertTemp': 'Alert Temp: @value',
          'highTemp': 'High Temp: @value',
          'lowTemp': 'Low Temp: @value',
          'temperatureSetting': 'Temperature Set Point(s)',
          'returnSetPoint': 'Return (Set Point)',
          'returnAlert': 'Return (Alert)',
          'dischargeTemp': 'Discharge Temperature',
          'suctionTemp': 'Suction Temperature',
          'pressuresSetting': 'Pressure Set Point(s)',
          'faultResetSetting': 'System Operation Settings',
          'autoManualResetSwitch': 'Fault Resetting',
          'manualReset': 'Manual\n Reset',
          'autoReset': ' Auto\nReset',
          'tempSensorsConfig': 'Temp Sensors Configuration',
          'pressureSensorsConfig': 'Pressure Sensors Configuration',
          'enableDisableConfig': 'Enable/Disable Configuration',
          'none': 'None',
          'suctionPressureSensor': 'Suction Pressure Sensor',
          'dischargePressureSensor': 'Discharge Pressure Sensor',
          'sensorConfig': 'Sensor Configuration',
          'pressureUnit': 'Pressure Unit',
          'sensorMaxRange': 'Sensor Max Range',
          'sensorOutputType': 'Sensor Output Type',
          'suctionPressureSwitch': 'Suction Pressure Switch',
          'dischargePressureSwitch': 'Discharge Pressure Switch',
          'offset': 'Offset:',
          'ampere_switch': 'Current Monitoring',
          'operation_mode_setting': 'Operation Mode Setting',
          'operation_mode_selection': 'Operating Mode Selection',
          'mode': 'Mode',
          'controlling': 'Controlling',
          'control_system': 'Control System',
          'monitoring_system': 'Monitoring System',
          'monitoring': 'Monitoring',
          'tripped': 'Tripped',
          'comp_fail_to_run': 'Comp. Fail to Run',
          'oil_sw_low': 'Oil (SW)-Low',
          'discharge_sw_high': 'Discharge (SW)-High',
          'suction_sw_low': 'Suction (SW)-Low',
          'comp_current_high': 'Comp. Current-High',
          'oil_ps_low': 'Oil (PS)-Low',
          'discharge_ps_high': 'Discharge (PS)-High',
          'suction_ps_low': 'Suction (PS)-Low',
          'discharge_ts_high': 'Discharge (TS)-High',
          'suction_ts_low': 'Suction (TS)-Low',
          'return_ts_high': 'Return (TS)-High',
          'auto_stopped': 'Auto Stopped',
          'restarting': 'Starting',
          'system_pressures_bar': 'System (PT-C) Pressures (bar)',
          'system_pressures_psi': 'System (PT-C) Pressures (PSI)',
          'temperature_sensors_configurations':
              'Temperature Sensors Configurations',
          'gas_selection': 'Gas Selection',
          'select_gas': 'Select Gas',
          'select_mode': 'Select Mode',
          'temp_sensors_configuration': 'Temp Sensors Configuration',
          'booster_pump': 'Booster Pump',
          'makeup_pump': 'Makeup Pump',
          'recirculation_pump': 'Circulation Pump',
          'control': 'Control',
          'system_operation_scheduling': 'System Operation Scheduling',
          'manual': 'Manual',
          'auto': 'Auto',
          'overhead_tank_water_level': 'Overhead Tank Water Level',
          'enabled': 'Enabled',
          'disabled': 'Disabled',
          'Pump': 'Pump',
          'notice': 'System Alert!',
          'your_mode_is_manual': 'System in Manual Mode',
          'cooler_comfort': 'Cooler & Comforter',
          'display_mode': 'Display Mode',
          'dark': 'Dark',
          'light': 'Light',
          'cooling': 'Cooling',
          'heating': 'Heating',
          'inner_fan_overload': 'Inner Fan Overload',
          'comp_overload': 'Comp Overload',
          'feedback_overload': 'Feedback Overload',
          'return_temp': 'Return \n Temp',
          'room_temp': 'Room \n Temp',
          'no': 'No',
          'yes': 'Yes',
          'delete_all_notifications_question':
              'Are you sure you want to delete all notifications?',
          'delete_all': 'Delete All?',
          'notifications': 'Notifications',
          'no_notifications_yet': 'No notifications',
          'condenser_overload': 'Condenser Overload',
          'compressor_overload': 'Compressor Overload',
          'heater_fail_to_run': 'Heater Fail To Run',
          'innerfan_fail_to_run': 'InnerFan Fail To Run',
          'suction_pressure_sensor': 'Suction Pressure Sensor',
          'discharge_pressure_sensor': 'Discharge Pressure Sensor',
          'heater_fan_feedback': 'Heater Fan Feedback',
          'inner_fan_feedback': 'Inner Fan Feedback',
          'compressor_feedback': 'Compressor Feedback',
          'system_delay': 'System Delay',
          'tempSensorsSetting': 'Temperature Offset Settings',
          'operation_control_selection': 'Operation Control',
          'return_temp1': 'Return Temp',
          'thermostat': 'Thermostat',
          'returnTsFail': 'Return (TS) Fail',
          'suctionTsFail': 'Suction (TS) Fail',
          'dischargeTsFail': 'Discharge (TS) Fail',
          'oilPsFail': 'Oil (PS) Fail',
          'dischargePsFail': 'Discharge (PS) Fail',
          'suctionPsFail': 'Suction (PS) Fail',
          'drainMaster': 'Drain Master',
          'severageMaster': 'Sewerage Master',
          'room_temp_alert': 'Room Temp Alert',
          'humidity_rh': 'Humidity (RH)',
          'system_parameters': 'System Parameters',
          'temp_alert': 'Temp Alert',
          'temp_set_point': 'Temp Set Point',
          'parameters_set_points': 'Parameters Set Points',
          'temperature_alert': 'Temperature Alert',
          'temperature_setpoint': 'Temperature Set Point',
          'humidity_setpoint': 'Humidity Set Point',
          'ac_unit_2': 'AC-2',
          'ac_unit_1': 'AC-1',
          'ac_units_status': 'AC Units Status',
          'overlap_delay': 'Overlap Delay',
          'ac_2_time': 'AC-2 Time',
          'ac_1_time': 'AC-1 Time',
          'ac_units_duty_times': 'AC Units Duty Times',
          'time_3': 'Time 3',
          'time_2': 'Time 2',
          'time_1': 'Time 1',
          'system': 'System',
          'ac_1_duty_time': 'AC-1 Duty Time',
          'ac_2_duty_time': 'AC-2 Duty Time',
          'overlap_delay_time': 'Overlap Delay Time',
            'minutes': 'Minutes',
     
        },
        // Arabic Translations
        'ar': {
           'minutes': 'دقائق',
          'system': 'النظام',
          'ac_1_duty_time': 'وقت عمل التكييف 1',
          'ac_2_duty_time': 'وقت عمل التكييف 2',
          'overlap_delay_time': 'وقت تأخير التداخل',
          'time_3': 'الوقت 3',
          'time_2': 'الوقت 2',
          'time_1': 'الوقت 1',
          'overlap_delay': 'تأخير التداخل',
          'ac_2_time': 'وقت التكييف 2',
          'ac_1_time': 'وقت التكييف 1',
          'ac_units_duty_times': 'أوقات عمل وحدات التكييف',
          'ac_unit_2': 'وحدة التكييف 2',
          'ac_unit_1': 'وحدة التكييف 1',
          'ac_units_status': 'حالة وحدات التكييف',
          'temperature_setpoint': 'نقطة ضبط الحرارة',
          'humidity_setpoint': 'نقطة ضبط الرطوبة',
          'temperature_alert': 'تنبيه درجة الحرارة',
          'parameters_set_points': 'نقاط ضبط المعلمات',
          'temp_alert': 'تنبيه الحرارة',
          'temp_set_point': 'نقطة ضبط الحرارة',
          'system_parameters': 'معلمات النظام',
          'humidity_rh': 'الرطوبة (RH)',
          'room_temp_alert': 'تنبيه درجة حرارة الغرفة',
          'drainMaster': 'رئيس التصريف',
          'severageMaster': 'رئيس الصرف الصحي',
          'oilPsFail': 'فشل ضغط الزيت',
          'dischargePsFail': 'فشل ضغط الطرد',
          'suctionPsFail': 'فشل ضغط الشفط',
          'returnTsFail': 'فشل حساس الرجوع',
          'suctionTsFail': 'فشل حساس الشفط',
          'dischargeTsFail': 'فشل حساس الطرد',
          'thermostat': 'منظم الحرارة',
          'return_temp1': 'درجة حرارة العودة',
          'operation_control_selection': 'اختيار التحكم في التشغيل',
          'tempSensorsSetting': 'إعدادات مستشعرات درجة الحرارة',
          'system_delay': 'تأخير النظام',
          'pump': 'حالة المضخة',
          'heater_fan_feedback': 'ملاحظات مروحة السخان',
          'inner_fan_feedback': 'ملاحظات المروحة الداخلية',
          'compressor_feedback': 'ملاحظات الضاغط',
          'suction_pressure_sensor': 'مستشعر ضغط الشفط',
          'discharge_pressure_sensor': 'مستشعر ضغط التصريف',
          'condenser_overload': 'زيادة الحمل على المكثف',
          'compressor_overload': 'زيادة الحمل على الضاغط',
          'heater_fail_to_run': 'فشل السخان في التشغيل',
          'innerfan_fail_to_run': 'فشل المروحة الداخلية في التشغيل',
          'no_notifications_yet': 'لا توجد إشعارات حتى الآن',
          'notifications': 'الإشعارات',
          'no': 'لا',
          'yes': 'نعم',
          'delete_all_notifications_question':
              'هل أنت متأكد أنك تريد حذف جميع الإشعارات؟',
          'delete_all': 'حذف الكل؟',
          'inner_fan_overload': 'زيادة حمل مروحة داخلية',
          'comp_overload': 'زيادة حمل الضاغط',
          'feedback_overload': 'زيادة حمل التغذية الراجعة',
          'return_temp': 'درجة حرارة \n العودة',
          'room_temp': 'درجة حرارة \n الغرفة',
          'cooling': 'تبريد',
          'heating': 'تدفئة',
          'display_mode': 'وضع العرض',
          'dark': 'مظلم',
          'light': 'ضوء',
          'cooler_comfort': 'مبرد وراحة',
          'enabled': 'مُفعل',
          'notice': 'تنبيه',
          'your_mode_is_manual': 'وضعك يدوي',
          'disabled': 'معطل',
          'select_mode': 'اختر الوضع',
          'overhead_tank_water_level': 'مستوى مياه الخزان العلوي',
          'manual': 'يدوي',
          'auto': 'تلقائي',
          'system_operation_scheduling': 'جدولة تشغيل النظام',
          'control': 'تحكم',
          'booster_pump': 'مضخة التعزيز',
          'makeup_pump': 'مضخة المكياج',
          'recirculation_pump': 'مضخة إعادة التدوير',
          'temp_sensors_configuration': 'تهيئة مستشعرات الحرارة',
          'select_gas': 'حدد الغاز',
          'gas_selection': 'اختيار الغاز',
          'temperature_sensors_configurations': 'تهيئة مستشعرات الحرارة',
          'system_pressures_bar': 'ضغوط النظام (PT-C) (bar)',
          'system_pressures_psi': 'ضغوط النظام (PT-C) (PSI)',
          'comp_fail_to_run': 'فشل الضاغط في التشغيل',
          'oil_sw_low': 'زيت (مفتاح) - منخفض',
          'discharge_sw_high': 'الطرد (مفتاح) - مرتفع',
          'suction_sw_low': 'الشفط (مفتاح) - منخفض',
          'comp_current_high': 'تيار الضاغط - مرتفع',
          'oil_ps_low': 'زيت (ضغط) - منخفض',
          'discharge_ps_high': 'الطرد (ضغط) - مرتفع',
          'suction_ps_low': 'الشفط (ضغط) - منخفض',
          'discharge_ts_high': 'الطرد (درجة الحرارة) - مرتفع',
          'suction_ts_low': 'الشفط (درجة الحرارة) - منخفض',
          'return_ts_high': 'العودة (درجة الحرارة) - مرتفع',
          'auto_stopped': 'توقف تلقائي',
          'restarting': 'يعيد التشغيل',
          'monitoring': 'المراقبة',
          'ampere_switch': 'مفتاح الأمبير',
          'operation_mode_setting': 'إعداد وضع التشغيل',
          'operation_mode_selection': 'اختيار وضع التشغيل',
          'mode': 'الوضع',
          'controlling': 'التحكم',
          'control_system': 'نظام التحكم',
          'monitoring_system': 'نظام المراقبة',
          'offset': 'الانحراف:',
          'dischargePressureSwitch': 'مفتاح ضغط الطرد',
          'suctionPressureSwitch': 'مفتاح ضغط الشفط',
          'sensorOutputType': 'نوع خرج المستشعر',
          'sensorMaxRange': 'المدى الأقصى للمستشعر',
          'pressureUnit': 'وحدة الضغط',
          'sensorConfig': 'تهيئة المستشعرات',
          'dischargePressureSensor': 'أجهزة استشعار ضغط الطرد',
          'suctionPressureSensor': 'أجهزة استشعار ضغط الشفط',
          'none': 'لا شيء',
          'tempSensorsConfig': 'إعداد مستشعرات الحرارة',
          'enableDisableConfig': 'تمكين/تعطيل الإعداد',
          'pressureSensorsConfig': 'إعداد مستشعرات الضغط',
          'autoReset': 'إعادة\nضبط تلقائي',
          'manualReset': 'إعادة\nضبط يدوي',
          'autoManualResetSwitch': 'مفتاح إعادة الضبط التلقائي/اليدوي',
          'faultResetSetting': 'إعدادات تشغيل النظام',
          'pressuresSetting': 'إعدادات الضغط',
          'suctionTemp': 'درجة حرارة السحب',
          'dischargeTemp': 'درجة حرارة التفريغ',
          'returnAlert': 'الرجوع (تنبيه)',
          'returnSetPoint': 'الرجوع (نقطة التعيين)',
          'temperatureSetting': 'إعداد درجة الحرارة',
          'setPoint': 'نقطة الضبط :',
          'alertTemp': 'درجة حرارة التنبيه: @value',
          'highTemp': 'درجة الحرارة العالية: @value',
          'lowTemp': 'درجة الحرارة المنخفضة: @value',
          'returnSp': 'العودة (نقطة الضبط)',
          'systemTempC': 'درجات حرارة النظام (°م)',
          'systemTempF': 'درجات حرارة النظام (°ف)',
          'systemPressurePsi': 'ضغوط النظام (رطل/بوصة²)',
          'systemPressureBar': 'ضغوط النظام (بار)',
          'compressorCurrent': 'تيار الضاغط (أ)',
          'pressureSwitches': 'مفاتيح الضغط',
          'tripped': 'تعطل',
          'autoStopped': 'توقف تلقائي',
          'Temp.': 'درجة الحرارة',
          'editDeviceName': 'تعديل اسم الجهاز',
          'waterTemp': 'درجة حرارة الماء',
          'waterTank': 'خزان الماء',
          'systemOff': 'إيقاف النظام',
          'ON': 'تشغيل',
          'OFF': 'إيقاف',
          'Alert Temperature': 'درجة حرارة التنبيه',
          'Set Point': 'نقطة الضبط',
          'automateControl': 'أتمتة التحكم',
          'fan': 'المروحة',
          'Pump': 'المضخة',
          'language': 'اللغة',
          'Power': 'الطاقة',
          'prsw': 'مفتاح الضغط',
          'oilPressureSensor': 'حساس ضغط الزيت',
          'oilPressureSwitch': 'مفتاح ضغط الزيت',
          'viewAccount': 'عرض الحساب',
          'dischargeSwitch': 'مفتاح التفريغ',
          'suctionSwitch': 'مفتاح الشف',
          'sensor': 'مستشعر',
          'confirm_proceed': 'هل أنت متأكد أنك تريد المتابعة؟',
          'confirm_enable': 'تفعيل مفتاح ضغط الزيت',
          'confirm_disable': 'إيقاف مفتاح ضغط الزيت',
          'temp': 'درجة الحرارة',
          'adjusting': 'يتم الضبط',
          'return_setpoint': 'نقطة الضبط المرتجعة',
          'winter_mode': 'وضع الشتاء',
          'days': 'الأيام',
          'hours': 'الساعات',
          'enable_button_to_set_schedule': 'تمكين الزر لتعيين الجدول الزمني',
          'schedule_damper': 'جدول الموانع',
          'slider_locked': 'المنزلق مقفل',
          ' ': 'حماية تدفق الهواء (CFM)',
          'Thermostat Error': 'خطأ في منظم الحرارة',
          'enable': 'تمكين',
          'disable': 'تعطيل',
          'error': 'خطأ',
          'wrong_password': 'كلمة المرور غير صحيحة',
          'unlock': 'فتح القفل',
          'password': 'كلمة المرور',
          'low_pressure': 'ضغط منخفض',
          'high_pressure': 'ضغط مرتفع',
          'high': 'مرتفع',
          'ok': 'حسنًا',
          'online': 'متصل',
          'offline': 'غير متصل',
          'home': 'الرئيسية',
          'device': 'جهاز',
          'add_devices': 'إضافة أجهزة',
          'me': 'الإعدادات',
          'device_list': 'قائمة الأجهزة',
          'dashboard_item_opacity': 'شفافية عنصر لوحة القيادة',
          'device_item_opacity': 'شفافية عنصر الجهاز',
          'select_season': 'اختر الموسم',
          'summer': 'صيف',
          'winter': 'شتاء',
          'on': 'تشغيل',
          'off': 'إيقاف',
          'set_point': 'نقطة الضبط',
          'supply_cfm': 'تدفق الهواء (CFM)',
          'signout': 'تسجيل الخروج',
          'value': 'القيمة',
          'set_temperature': 'ضبط درجة الحرارة',
          'delete_device_prompt': 'هل أنت متأكد أنك تريد حذف هذا الجهاز؟',
          'cancel': 'إلغاء',
          'delete': 'حذف',
          'delete_device': 'حذف الجهاز',
          'Schedule': 'الجدول',
          'CFM': 'CFM',
          'Mode': 'الوضع',
          'Season': 'الموسم',
          'Switch': 'مفتاح',
          'Room Temp.': 'درجة حرارة الغرفة',
          'Enter Password': 'أدخل كلمة المرور',
          'Submit': 'إرسال',
          'summer_mode': 'وضع الصيف',
          'aqua': 'أكوا',
          'water_level': 'مستوى المياه',
          'hi': 'مرتفع',
          'mid': 'منتصف',
          'low': 'منخفض',
          'cooler': 'مبرد',
          'boiler': 'غلاية',
          'comfort': 'راحة',
          'booster': 'معزز',
          'makeup': 'ماك أب',
          'recirculor': 'مدور',
          'settings': 'الإعدادات',
          'compressor': 'ضاغط',
          'Target': 'درجة الحرارة المستهدفة',
          'temperature': 'درجة الحرارة',
          'suction': 'شفط',
          'discharge': 'تصريف',
          'supply': 'تزويد',
          'return': 'رجوع',
          'pressure': 'الضغط',
          'oil': 'زيت',
          'phase_1': 'الطور 1',
          'phase_2': 'الطور 2',
          'phase_3': 'الطور 3',
          'temperatures': 'درجات الحرارة',
          'pressures': 'الضغوط',
          'currents': 'التيارات',
          'return_setting': 'إعداد الرجوع',
          'supply_setting': 'إعداد التزويد',
          'suction_setting': 'إعداد الشفط',
          'discharge_setting': 'إعداد التصريف',
          'low_temperature': 'درجة حرارة منخفضة',
          'high_temperature': 'درجة حرارة مرتفعة',
          'compressor_status': 'حالة الضاغط',
          'suction_pressure_setting': 'إعداد ضغط الشفط',
          'discharge_pressure_setting': 'إعداد ضغط التصريف',
          'oil_pressure_setting': 'إعداد ضغط الزيت',
          'current_setting': 'إعداد التيار',
          'high_ampere': 'تيار عالي',
          'close': 'إغلاق',
          'open': 'فتح',
          'fan_controller': 'وحدة تحكم المروحة',
          'pump_controller': 'وحدة تحكم المضخة',
          'qr_code_scanner': 'ماسح رمز الاستجابة السريعة',
          'home_pages': 'الصفحات الرئيسية',
          'dark_mode': 'الوضع الداكن',
          'view_account': 'عرض الحساب',
          'bita_homes': 'بيتا هومز',
          'name': 'الاسم',
          'edit_name': 'تعديل الاسم',
          'enter_new_name': 'أدخل الاسم الجديد',
          'save': 'حفظ',
          'logout': 'تسجيل الخروج',
        },
      };
}
